import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/components/Footer'
import { useContext } from 'react'
import { AuthContext } from '@/context/auth/AuthContext'
import NavBar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { signIn } = useContext(AuthContext)
  return (
    <>
      <Head>
        <title>Codelife</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-[100vh] w-full flex-col bg-codelife-green-500">
        <NavBar />
        <h1 className='font-merry text-5xl font-bold text-codelife-black-600 '>Aprenda a desenvolver websites</h1>
        <p className='mb-8'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. A ex nisi aliquid adipisci, ratione nulla exercitationem porro! Perspiciatis quae voluptatem numquam quis officiis, nobis, quaerat perferendis hic, ad dolore deserunt.</p>
        <button onClick={() => signIn({ email: "teste@teste.com", password: "123456" })
        } className='rounded-sm bg-codelife-green-400 text-lg text-codelife-black-700'>SIGN IN</button>
        <Footer />
      </main>
    </>
  )
}
